[package]
name = "streaming-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
aeron-cache-embedded-client = { path = "../../../libraries/rust" }
tokio = { version = "1", features = ["full"] }
